low_rho : 10
high_rho : 500
num_peers : 2
babasi_albert_m : 1
slow_cij_val : 5000
high_cij_val : 100000
dij_cij_factor : 96
slow_fraction : 0
txn_inter_arrival_time : 100000
too_many_peers : False
net_mean_mining_time : 600000
hashing_fractions : 
  - 0.333
  - 0.667
mining_fee : 20
max_events : 20000
text_files_folder : "Block_Arrivals"
attacker :
attacker_connection : 0