low_rho : 10
high_rho : 500
num_peers : 100
babasi_albert_m : 
slow_cij_val : 5000
high_cij_val : 100000
dij_cij_factor : 96
slow_fraction : 0.3
txn_inter_arrival_time : 100000
too_many_peers : True
net_mean_mining_time : 600000
mean_mining_time : 
  - 300000
  - 300000
mining_fee : 20
max_events : 500000
text_files_folder : "Block_Arrivals"
attacker : None
attacker_connection : 0