low_rho : 10
high_rho : 500
num_peers : 5
slow_cij_val : 5000
high_cij_val : 100000
dij_cij_factor : 96
slow_fraction : 0.2
txn_inter_arrival_time : 100000
too_many_peers : False
mean_mining_time : 
  - 300000
  - 300000
  - 400000
  - 600000
  - 600000
mining_fee : 20
max_events : 50000
text_files_folder : "Block_Arrivals"
