low_rho : 10
high_rho : 500
num_peers : 5
slow_cij_val : 5000
high_cij_val : 100000
dij_cij_factor : 96
slow_fraction : 0.2
babasi_albert_m : 2
txn_inter_arrival_time : 100000
too_many_peers : False
net_mean_mining_time : 600000
mean_mining_time : 
  - 0.2
  - 0.1
  - 0.2
  - 0.3
  - 0.2
mining_fee : 20
max_events : 50000
text_files_folder : "Block_Arrivals"
attacker :
attacker_connection : 0